### ISSUE TITLE
emph命令得到的格式为下划线

### ISSUE THREAD

**Issue by atxy-blip** [nju-lug/NJUThesisUndergraduate#2]

**Comment by FengChendian** [comment]
![图片](https://user-images.githubusercontent.com/37545115/132167256-cdcfd15f-38df-44c2-929f-969be16186a6.png)

**Comment by FengChendian** [comment]
ulem用于生成摘要部分下划线

**Comment by myandeg** [comment]
调包时添加参数[normalem]即可保持原来的用斜体表示强调
[ref](https://tex.stackexchange.com/questions/104058/getting-emph-back-to-normal-after-loading-ulem)
